version: "3.8"
services:
  tinyproxy:
    container_name: tiny_proxy
    image: newnius/tinyproxy
    ports:
      - "8888:8888"
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
    restart: unless-stopped
